export const DOG_BREEDS = [
  "Mieszaniec",
  "Akita",
  "Alaskan malamute",
  "Amstaff",
  "Australian shepherd",
  "Basenji",
  "Beagle",
  "Berneński pies pasterski",
  "Bichon frise",
  "Border collie",
  "Bokser",
  "Buldog angielski",
  "Buldog francuski",
  "Bull terrier",
  "Cane corso",
  "Cavalier king charles spaniel",
  "Chihuahua",
  "Chow chow",
  "Cocker spaniel",
  "Dalmatyńczyk",
  "Doberman",
  "Golden retriever",
  "Hawańczyk",
  "Husky syberyjski",
  "Jack russell terrier",
  "Jamnik",
  "Labrador retriever",
  "Maltańczyk",
  "Mops",
  "Nowofundland",
  "Owczarek australijski",
  "Owczarek belgijski",
  "Owczarek niemiecki",
  "Owczarek podhalański",
  "Papillon",
  "Pekińczyk",
  "Pinczer miniaturowy",
  "Pomeranian",
  "Pudel",
  "Rottweiler",
  "Samoyed",
  "Shiba inu",
  "Shih tzu",
  "Sznaucer",
  "West highland white terrier",
  "Wyżeł weimarski",
  "Yorkshire terrier"
] as const;
