export const PET_ALLERGIES = [
  "Kurczak",
  "Wołowina",
  "Wieprzowina",
  "Jagnięcina",
  "Ryby",
  "Jaja",
  "Nabiał",
  "Pszenica",
  "Gluten",
  "Kukurydza",
  "Soja",
  "Ryż",
  "Roztocza kurzu",
  "Pyłki traw",
  "Pyłki drzew",
  "Pleśń",
  "Pchły",
  "Ukąszenia owadów",
  "Szampony i kosmetyki",
  "Lateks",
  "Penicylina",
  "Niesteroidowe leki przeciwzapalne"
] as const;
