FROM node:22-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG EXPO_PUBLIC_API_URL=http://localhost:4000/api
ARG EXPO_PUBLIC_AUTH_TOKEN_KEY=auth_token
ARG EXPO_PUBLIC_REFRESH_TOKEN_KEY=refresh_token
ARG EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=
ARG EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID=
ARG EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID=
ARG EXPO_PUBLIC_GOOGLE_REDIRECT_URI=http://localhost:8081

ENV EXPO_PUBLIC_API_URL=$EXPO_PUBLIC_API_URL \
    EXPO_PUBLIC_AUTH_TOKEN_KEY=$EXPO_PUBLIC_AUTH_TOKEN_KEY \
    EXPO_PUBLIC_REFRESH_TOKEN_KEY=$EXPO_PUBLIC_REFRESH_TOKEN_KEY \
    EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=$EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID \
    EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID=$EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID \
    EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID=$EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID \
    EXPO_PUBLIC_GOOGLE_REDIRECT_URI=$EXPO_PUBLIC_GOOGLE_REDIRECT_URI

RUN npx expo export --platform web

FROM nginx:1.27-alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8081

HEALTHCHECK --interval=10s --timeout=3s --start-period=10s --retries=6 \
  CMD wget -qO- http://127.0.0.1:8081/ >/dev/null || exit 1
